name: package test and docs test

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install casatools
        pip install casatasks

    - name Install vanilla package
      run: |
        pip install .
    
    - name: Install test deps 
      run: |
        pip install .[test]
    
    - name: Test with pytest
      run: | 
          pytest
    
# if all tests succeed, then
# make sure the docs build OK
# (but don't deploy to gh-pages)
  docs:
    needs: tests
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install doc deps
        run: |
          pip install --extra-index-url https://casa-pip.nrao.edu/repository/pypi-casa-release/simple .[docs]
      # https://open-bitbucket.nrao.edu/projects/CASA/repos/casa6/browse/casatools/casadata.md
      - name: Update CASA runtime data
        run: | 
          python -m casatools --update-user-data
      - name: Install Pandoc dependency for nbconvert 
        run: |
          sudo apt-get install pandoc
      - name: Clean docs build 
        run: |
          make -C docs clean
      - name: Cache/Restore the AS 209 measurement set
        uses: actions/cache@v2
        env:
          cache-name: cache-AS209
        with:
          # files are stored in docs/tutorials/AS209_MS
          path: docs/tutorials/AS209_MS
          # we want to hash off of the build script
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('docs/tutorials/dl_and_tclean_AS209.py') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build the docs
        run: |
          make -C docs html 

      